
 
- name: Install emacs-nox
  become: true
  apt:
    name: emacs-nox
    state: present   

- name: Creates the bashrc 
  template:
    src: bashrc.j2
    dest: /home/azureuser/.bashrc

- name: Create username user
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Update authorized_keys
  become: true
  template:
    src: authorized_keys.j2
    dest: /home/{{ username }}/.ssh/authorized_keys    
